<div class="container d-flex align-items-center justify-content-center vh-100">
    <div class="row justify-content-center w-100">
        <div class="col-md-6 col-lg-5 bg-white p-4 rounded shadow">
            <h1 class="text-dark fw-bold text-start pb-3">Login</h1>
            <form method="post" action="/login.php">
                <!-- Email Input -->
                <div class="mb-3">
                    <label for="email" class="form-label fw-medium">Email</label>
                    <input type="email" name="email" id="email" class="form-control bg-success-subtle border-secondary" placeholder="Email" required>
                </div>

                <!-- Password Input -->
                <div class="mb-3">
                    <label for="password" class="form-label fw-medium">Password</label>
                    <input type="password" name="password" id="password" class="form-control bg-success-subtle border-secondary" placeholder="Password" required>
                </div>

                <!-- Log in Button -->
                <div class="d-grid">
                    <button type="submit" class="btn btn-success">Log in</button>
                </div>
            </form>

            <!-- Sign up Link -->
            <p class="text-success text-center pt-2">Don't have an account?</p>

            <!-- Sign up Button -->
            <div class="d-grid">
                <a href="/signup.php" class="btn btn-outline-success">Sign up</a>
            </div>
        </div>
    </div>
</div>