<?php
require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../models/User.php';
?>

<div class="d-flex flex-grow-1 flex-column align-items-center justify-content-center bg-light">
    <div class="card w-100" style="max-width: 40rem;">
        <div class="card-body">
            <div class="d-flex align-items-center gap-2 pb-4">
                <h1 class="text-dark fw-bold mb-0">Edit Profile</h1>
                <i class="fa-solid fa-pencil fs-4"></i>
            </div>

            <form action="<?= PREFIX ?>/profile.php" method="post">
                <div class="row">
                    <!-- First Name Field -->
                    <div class="col-md-6 mb-3">
                        <label for="first_name" class="form-label">First Name</label>
                        <input type="text" id="first_name" name="first_name" placeholder="First Name" required
                            value="<?= User::fromSession()->firstName ?>"
                            class="form-control" />
                    </div>

                    <!-- Last Name Field -->
                    <div class="col-md-6 mb-3">
                        <label for="last_name" class="form-label">Last Name</label>
                        <input type="text" id="last_name" name="last_name" placeholder="Last Name" required
                            value="<?= User::fromSession()->lastName ?>"
                            class="form-control" />
                    </div>

                    <!-- Email Input -->
                    <div class="col-md-12 mb-3">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" id="email" name="email" placeholder="Email" required
                            value="<?= User::fromSession()->email ?>"
                            class="form-control" />
                    </div>

                    <!-- Change Password Input -->
                    <div class="col-md-12 mb-3">
                        <label for="password" class="form-label">New Password</label>
                        <input type="password" id="password" name="password" placeholder="Change Password" required
                            class="form-control" />
                    </div>
                </div>

                <div class="d-flex justify-content-between mt-4">
                    <!-- Log out Button -->
                    <a href="<?= PREFIX ?>/logout.php" class="btn btn-outline-danger">
                        Log out
                    </a>

                    <!-- Save Changes Button -->
                    <button type="submit" class="btn btn-success">
                        Save changes
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>